name: "check-rs"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-rs:
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        rust-version: ["1.81.0", "stable"]

    steps:
      - uses: actions/checkout@v4

      - name: Use Rust ${{ matrix.rust-version }}
        uses: dtolnay/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          components: rustfmt, clippy

      - name: Run Clippy checks
        run: "cargo clippy --all-targets --all-features -- -D warnings"

      - name: Run tests
        run: "cargo test"
